name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push PostgreSQL image
        run: |
          docker-compose -f docker-compose.yml build postgres
          docker-compose -f docker-compose.yml push postgres

      - name: Build and push Keycloak image
        run: |
          docker-compose -f docker-compose.yml build keycloak
          docker-compose -f docker-compose.yml push keycloak

      - name: Build and push React App image
        run: |
          docker-compose -f docker-compose.yml build react-app
          docker-compose -f docker-compose.yml push react-app

      - name: Build and push Spring Boot App image
        run: |
          docker-compose -f docker-compose.yml build spring-boot-app
          docker-compose -f docker-compose.yml push spring-boot-app
